### ISSUE TITLE
Secure With HTTPS And Force HTTPS Redirect

### ISSUE THREAD

**Issue by conatus** [commonknowledge/website#1]
HTTPS should [be automatic with Netlify](https://www.netlify.com/docs/ssl/) but seems to be in an [odd state right now](https://commonknowledge.coop/) - perhaps the machinery is working.

Seems you can force SSL in the interface - here is the corresponding API - https://www.netlify.com/docs/api/

**Comment by janbaykara** [comment]
Good spot 👍Solved with automated Netlify HTTPS config.
