### ISSUE TITLE
Move to using pure Emotion, not theme-ui which is a little over cooked

### ISSUE THREAD

**Issue by conatus** [commonknowledge/website#17]
Happy to chat this through but felt that this worked well in November and December. I personally find theme-ui quite confusing.

**Comment by chrisdevereux** [comment]
I find that when I use pure emotion, I often end up re-implementing theme ui. Although think if we use theme-ui we should go all in on it

**Comment by conatus** [comment]
There is a bit of a mix in play at the moment if you look at the code, which was the result of a bit of a rush. 

If you feel it is useful, I am willing to give it a try again as long as someone else strips it out if it seems a bit clumsy in the end.

**Comment by conatus** [comment]
We use Theme UI for everything now, so this is redudant.
