### ISSUE TITLE
Add links to coop resources

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/website#6]
#### Ops
- [x] https://github.com/commonknowledge
- [x] https://git.coop/commonknowledge
- [ ] https://trello.com/commonknowledge

#### Comms
- [x] https://twitter.com/platformpolitic
- [x] https://www.facebook.com/Common-Knowledge-1825534697572895
- [ ] https://commonknowledge.slack.com/
- [X] hello@commonknowledge.coop

#### Jobs
- [ ] https://www.linkedin.com/company/commonknowledge/
- [ ] https://angel.co/commonknowledge

#### Co-op information
- [ ] https://beta.companieshouse.gov.uk/company/11620742
- [ ] Company articles

**Comment by janbaykara** [comment]
@conatus I never found the time to turn the Company Articles into Markdown. Did you?

I'd also like to put our company information on the website; any objections?

**Comment by conatus** [comment]
Didn't do the conversion into Markdown. I sort of wanted to take the Google Doc back to the original version for commit one, then do our ammendments as commit two to show how we edited it.

I don't think I have any objections but might be nice to do all the other stuff first.

**Comment by conatus** [comment]
Reader: we eventually did convert the company articles to Markdown and in the process found they have errors.

https://github.com/commonknowledge/articles
