### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/website#9]

**Comment by janbaykara** [comment]
@conatus Whilst I'm not overly keen on using Google Analytics, I'm swayed towards it for simple no-config data capture. But you previously mentioned you had a preference?

**Comment by conatus** [comment]
I'd suggest we whack in [Segment](https://segment.com/) as a first step, though it seems a bit tangential.

This provides a layer between generally collecting analytics and a specific instantiation. You can switch things on and off very easily and it [supports almost everything](https://segment.com/catalog/#integrations/all), including raw information into Postgres etc. We can then try a bunch of stuff and find what we like with zero deployment and take an experimental approach. It also keeps it more managed than a general mess analytics can become.

In terms of where to go then we can try a bunch of things. As our needs are modest, I'd be interested to find a very simple tool which has the absolute barest metrics. Downstream from GA. Fortunately, the Segment catalog let's us pretty much know what the market looks like!

For applications, [Heap](https://heapanalytics.com/) is my favoured solution as it allows retroactive analysis without needing to know what you want to learn and has zero setup. We aren't even close yet and it needs more consideration, including along political lines.

Out of interest does Netlify give you access to logs?
